# Generated by Django 3.0 on 2019-12-08 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_server', '0002_filemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='is_upload_qiniu',
            field=models.BooleanField(default=False),
        ),
    ]
